<?php
/**
 * ServicesApi
 * PHP version 5
 *
 * @category Class
 * @package  DocPlanner\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Docplanner Integrations API
 *
 * Welcome to Docplanner Integrations [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API!  This API gives You the ability to build Your own application and integrate it with Docplanner services.
 *
 * OpenAPI spec version: 1.0.29
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocPlanner\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use DocPlanner\Client\ApiException;
use DocPlanner\Client\Configuration;
use DocPlanner\Client\HeaderSelector;
use DocPlanner\Client\ObjectSerializer;

/**
 * ServicesApi Class Doc Comment
 *
 * @category Class
 * @package  DocPlanner\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServicesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addAddressService
     *
     * @param  \DocPlanner\Client\Model\AddAddressServiceRequest $body body (required)
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function addAddressService($body, $facility_id, $doctor_id, $address_id)
    {
        $this->addAddressServiceWithHttpInfo($body, $facility_id, $doctor_id, $address_id);
    }

    /**
     * Operation addAddressServiceWithHttpInfo
     *
     * @param  \DocPlanner\Client\Model\AddAddressServiceRequest $body (required)
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function addAddressServiceWithHttpInfo($body, $facility_id, $doctor_id, $address_id)
    {
        $returnType = '';
        $request = $this->addAddressServiceRequest($body, $facility_id, $doctor_id, $address_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation addAddressServiceAsync
     *
     * 
     *
     * @param  \DocPlanner\Client\Model\AddAddressServiceRequest $body (required)
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addAddressServiceAsync($body, $facility_id, $doctor_id, $address_id)
    {
        return $this->addAddressServiceAsyncWithHttpInfo($body, $facility_id, $doctor_id, $address_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addAddressServiceAsyncWithHttpInfo
     *
     * 
     *
     * @param  \DocPlanner\Client\Model\AddAddressServiceRequest $body (required)
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addAddressServiceAsyncWithHttpInfo($body, $facility_id, $doctor_id, $address_id)
    {
        $returnType = '';
        $request = $this->addAddressServiceRequest($body, $facility_id, $doctor_id, $address_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'addAddressService'
     *
     * @param  \DocPlanner\Client\Model\AddAddressServiceRequest $body (required)
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function addAddressServiceRequest($body, $facility_id, $doctor_id, $address_id)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling addAddressService'
            );
        }
        // verify the required parameter 'facility_id' is set
        if ($facility_id === null || (is_array($facility_id) && count($facility_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $facility_id when calling addAddressService'
            );
        }
        // verify the required parameter 'doctor_id' is set
        if ($doctor_id === null || (is_array($doctor_id) && count($doctor_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $doctor_id when calling addAddressService'
            );
        }
        // verify the required parameter 'address_id' is set
        if ($address_id === null || (is_array($address_id) && count($address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_id when calling addAddressService'
            );
        }

        $resourcePath = '/facilities/{facility_id}/doctors/{doctor_id}/addresses/{address_id}/services';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($facility_id !== null) {
            $resourcePath = str_replace(
                '{' . 'facility_id' . '}',
                ObjectSerializer::toPathValue($facility_id),
                $resourcePath
            );
        }
        // path params
        if ($doctor_id !== null) {
            $resourcePath = str_replace(
                '{' . 'doctor_id' . '}',
                ObjectSerializer::toPathValue($doctor_id),
                $resourcePath
            );
        }
        // path params
        if ($address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'address_id' . '}',
                ObjectSerializer::toPathValue($address_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.error+docplanner+json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.error+docplanner+json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteAddressService
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteAddressService($facility_id, $doctor_id, $address_id, $address_service_id)
    {
        $this->deleteAddressServiceWithHttpInfo($facility_id, $doctor_id, $address_id, $address_service_id);
    }

    /**
     * Operation deleteAddressServiceWithHttpInfo
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteAddressServiceWithHttpInfo($facility_id, $doctor_id, $address_id, $address_service_id)
    {
        $returnType = '';
        $request = $this->deleteAddressServiceRequest($facility_id, $doctor_id, $address_id, $address_service_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteAddressServiceAsync
     *
     * 
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAddressServiceAsync($facility_id, $doctor_id, $address_id, $address_service_id)
    {
        return $this->deleteAddressServiceAsyncWithHttpInfo($facility_id, $doctor_id, $address_id, $address_service_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteAddressServiceAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAddressServiceAsyncWithHttpInfo($facility_id, $doctor_id, $address_id, $address_service_id)
    {
        $returnType = '';
        $request = $this->deleteAddressServiceRequest($facility_id, $doctor_id, $address_id, $address_service_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteAddressService'
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteAddressServiceRequest($facility_id, $doctor_id, $address_id, $address_service_id)
    {
        // verify the required parameter 'facility_id' is set
        if ($facility_id === null || (is_array($facility_id) && count($facility_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $facility_id when calling deleteAddressService'
            );
        }
        // verify the required parameter 'doctor_id' is set
        if ($doctor_id === null || (is_array($doctor_id) && count($doctor_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $doctor_id when calling deleteAddressService'
            );
        }
        // verify the required parameter 'address_id' is set
        if ($address_id === null || (is_array($address_id) && count($address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_id when calling deleteAddressService'
            );
        }
        // verify the required parameter 'address_service_id' is set
        if ($address_service_id === null || (is_array($address_service_id) && count($address_service_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_service_id when calling deleteAddressService'
            );
        }

        $resourcePath = '/facilities/{facility_id}/doctors/{doctor_id}/addresses/{address_id}/services/{address_service_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($facility_id !== null) {
            $resourcePath = str_replace(
                '{' . 'facility_id' . '}',
                ObjectSerializer::toPathValue($facility_id),
                $resourcePath
            );
        }
        // path params
        if ($doctor_id !== null) {
            $resourcePath = str_replace(
                '{' . 'doctor_id' . '}',
                ObjectSerializer::toPathValue($doctor_id),
                $resourcePath
            );
        }
        // path params
        if ($address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'address_id' . '}',
                ObjectSerializer::toPathValue($address_id),
                $resourcePath
            );
        }
        // path params
        if ($address_service_id !== null) {
            $resourcePath = str_replace(
                '{' . 'address_service_id' . '}',
                ObjectSerializer::toPathValue($address_service_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.error+docplanner+json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.error+docplanner+json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAddressService
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \DocPlanner\Client\Model\AddressService
     */
    public function getAddressService($facility_id, $doctor_id, $address_id, $address_service_id)
    {
        list($response) = $this->getAddressServiceWithHttpInfo($facility_id, $doctor_id, $address_id, $address_service_id);
        return $response;
    }

    /**
     * Operation getAddressServiceWithHttpInfo
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \DocPlanner\Client\Model\AddressService, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAddressServiceWithHttpInfo($facility_id, $doctor_id, $address_id, $address_service_id)
    {
        $returnType = '\DocPlanner\Client\Model\AddressService';
        $request = $this->getAddressServiceRequest($facility_id, $doctor_id, $address_id, $address_service_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\AddressService',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAddressServiceAsync
     *
     * 
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAddressServiceAsync($facility_id, $doctor_id, $address_id, $address_service_id)
    {
        return $this->getAddressServiceAsyncWithHttpInfo($facility_id, $doctor_id, $address_id, $address_service_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAddressServiceAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAddressServiceAsyncWithHttpInfo($facility_id, $doctor_id, $address_id, $address_service_id)
    {
        $returnType = '\DocPlanner\Client\Model\AddressService';
        $request = $this->getAddressServiceRequest($facility_id, $doctor_id, $address_id, $address_service_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAddressService'
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAddressServiceRequest($facility_id, $doctor_id, $address_id, $address_service_id)
    {
        // verify the required parameter 'facility_id' is set
        if ($facility_id === null || (is_array($facility_id) && count($facility_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $facility_id when calling getAddressService'
            );
        }
        // verify the required parameter 'doctor_id' is set
        if ($doctor_id === null || (is_array($doctor_id) && count($doctor_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $doctor_id when calling getAddressService'
            );
        }
        // verify the required parameter 'address_id' is set
        if ($address_id === null || (is_array($address_id) && count($address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_id when calling getAddressService'
            );
        }
        // verify the required parameter 'address_service_id' is set
        if ($address_service_id === null || (is_array($address_service_id) && count($address_service_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_service_id when calling getAddressService'
            );
        }

        $resourcePath = '/facilities/{facility_id}/doctors/{doctor_id}/addresses/{address_id}/services/{address_service_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($facility_id !== null) {
            $resourcePath = str_replace(
                '{' . 'facility_id' . '}',
                ObjectSerializer::toPathValue($facility_id),
                $resourcePath
            );
        }
        // path params
        if ($doctor_id !== null) {
            $resourcePath = str_replace(
                '{' . 'doctor_id' . '}',
                ObjectSerializer::toPathValue($doctor_id),
                $resourcePath
            );
        }
        // path params
        if ($address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'address_id' . '}',
                ObjectSerializer::toPathValue($address_id),
                $resourcePath
            );
        }
        // path params
        if ($address_service_id !== null) {
            $resourcePath = str_replace(
                '{' . 'address_service_id' . '}',
                ObjectSerializer::toPathValue($address_service_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.docplanner+json; charset=UTF-8', 'application/vnd.error+docplanner+json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.docplanner+json; charset=UTF-8', 'application/vnd.error+docplanner+json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAddressServices
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  \DateTime $start Slot start date (parameter must be urlencoded before sending request). Limits results to only those linked to slots that start on that date. (optional)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \DocPlanner\Client\Model\AddressServices
     */
    public function getAddressServices($facility_id, $doctor_id, $address_id, $start = null)
    {
        list($response) = $this->getAddressServicesWithHttpInfo($facility_id, $doctor_id, $address_id, $start);
        return $response;
    }

    /**
     * Operation getAddressServicesWithHttpInfo
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  \DateTime $start Slot start date (parameter must be urlencoded before sending request). Limits results to only those linked to slots that start on that date. (optional)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \DocPlanner\Client\Model\AddressServices, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAddressServicesWithHttpInfo($facility_id, $doctor_id, $address_id, $start = null)
    {
        $returnType = '\DocPlanner\Client\Model\AddressServices';
        $request = $this->getAddressServicesRequest($facility_id, $doctor_id, $address_id, $start);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\AddressServices',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAddressServicesAsync
     *
     * 
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  \DateTime $start Slot start date (parameter must be urlencoded before sending request). Limits results to only those linked to slots that start on that date. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAddressServicesAsync($facility_id, $doctor_id, $address_id, $start = null)
    {
        return $this->getAddressServicesAsyncWithHttpInfo($facility_id, $doctor_id, $address_id, $start)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAddressServicesAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  \DateTime $start Slot start date (parameter must be urlencoded before sending request). Limits results to only those linked to slots that start on that date. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAddressServicesAsyncWithHttpInfo($facility_id, $doctor_id, $address_id, $start = null)
    {
        $returnType = '\DocPlanner\Client\Model\AddressServices';
        $request = $this->getAddressServicesRequest($facility_id, $doctor_id, $address_id, $start);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAddressServices'
     *
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  \DateTime $start Slot start date (parameter must be urlencoded before sending request). Limits results to only those linked to slots that start on that date. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAddressServicesRequest($facility_id, $doctor_id, $address_id, $start = null)
    {
        // verify the required parameter 'facility_id' is set
        if ($facility_id === null || (is_array($facility_id) && count($facility_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $facility_id when calling getAddressServices'
            );
        }
        // verify the required parameter 'doctor_id' is set
        if ($doctor_id === null || (is_array($doctor_id) && count($doctor_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $doctor_id when calling getAddressServices'
            );
        }
        // verify the required parameter 'address_id' is set
        if ($address_id === null || (is_array($address_id) && count($address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_id when calling getAddressServices'
            );
        }

        $resourcePath = '/facilities/{facility_id}/doctors/{doctor_id}/addresses/{address_id}/services';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($start !== null) {
            $queryParams['start'] = ObjectSerializer::toQueryValue($start, 'date-time');
        }

        // path params
        if ($facility_id !== null) {
            $resourcePath = str_replace(
                '{' . 'facility_id' . '}',
                ObjectSerializer::toPathValue($facility_id),
                $resourcePath
            );
        }
        // path params
        if ($doctor_id !== null) {
            $resourcePath = str_replace(
                '{' . 'doctor_id' . '}',
                ObjectSerializer::toPathValue($doctor_id),
                $resourcePath
            );
        }
        // path params
        if ($address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'address_id' . '}',
                ObjectSerializer::toPathValue($address_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.docplanner+json; charset=UTF-8', 'application/vnd.error+docplanner+json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.docplanner+json; charset=UTF-8', 'application/vnd.error+docplanner+json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getServices
     *
     * @param  \DocPlanner\Client\Model\ServicesScopes[] $with with (optional)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \DocPlanner\Client\Model\Services
     */
    public function getServices($with = null)
    {
        list($response) = $this->getServicesWithHttpInfo($with);
        return $response;
    }

    /**
     * Operation getServicesWithHttpInfo
     *
     * @param  \DocPlanner\Client\Model\ServicesScopes[] $with (optional)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \DocPlanner\Client\Model\Services, HTTP status code, HTTP response headers (array of strings)
     */
    public function getServicesWithHttpInfo($with = null)
    {
        $returnType = '\DocPlanner\Client\Model\Services';
        $request = $this->getServicesRequest($with);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Services',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getServicesAsync
     *
     * 
     *
     * @param  \DocPlanner\Client\Model\ServicesScopes[] $with (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getServicesAsync($with = null)
    {
        return $this->getServicesAsyncWithHttpInfo($with)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getServicesAsyncWithHttpInfo
     *
     * 
     *
     * @param  \DocPlanner\Client\Model\ServicesScopes[] $with (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getServicesAsyncWithHttpInfo($with = null)
    {
        $returnType = '\DocPlanner\Client\Model\Services';
        $request = $this->getServicesRequest($with);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getServices'
     *
     * @param  \DocPlanner\Client\Model\ServicesScopes[] $with (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getServicesRequest($with = null)
    {

        $resourcePath = '/services';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($with !== null) {
            $queryParams['with'] = ObjectSerializer::toQueryValue($with, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.docplanner+json; charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.docplanner+json; charset=UTF-8'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateAddressService
     *
     * @param  \DocPlanner\Client\Model\UpdateAddressServiceRequest $body body (required)
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \DocPlanner\Client\Model\AddressService
     */
    public function updateAddressService($body, $facility_id, $doctor_id, $address_id, $address_service_id)
    {
        list($response) = $this->updateAddressServiceWithHttpInfo($body, $facility_id, $doctor_id, $address_id, $address_service_id);
        return $response;
    }

    /**
     * Operation updateAddressServiceWithHttpInfo
     *
     * @param  \DocPlanner\Client\Model\UpdateAddressServiceRequest $body (required)
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \DocPlanner\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \DocPlanner\Client\Model\AddressService, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateAddressServiceWithHttpInfo($body, $facility_id, $doctor_id, $address_id, $address_service_id)
    {
        $returnType = '\DocPlanner\Client\Model\AddressService';
        $request = $this->updateAddressServiceRequest($body, $facility_id, $doctor_id, $address_id, $address_service_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\AddressService',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DocPlanner\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateAddressServiceAsync
     *
     * 
     *
     * @param  \DocPlanner\Client\Model\UpdateAddressServiceRequest $body (required)
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAddressServiceAsync($body, $facility_id, $doctor_id, $address_id, $address_service_id)
    {
        return $this->updateAddressServiceAsyncWithHttpInfo($body, $facility_id, $doctor_id, $address_id, $address_service_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateAddressServiceAsyncWithHttpInfo
     *
     * 
     *
     * @param  \DocPlanner\Client\Model\UpdateAddressServiceRequest $body (required)
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAddressServiceAsyncWithHttpInfo($body, $facility_id, $doctor_id, $address_id, $address_service_id)
    {
        $returnType = '\DocPlanner\Client\Model\AddressService';
        $request = $this->updateAddressServiceRequest($body, $facility_id, $doctor_id, $address_id, $address_service_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateAddressService'
     *
     * @param  \DocPlanner\Client\Model\UpdateAddressServiceRequest $body (required)
     * @param  string $facility_id ID of the Facility (required)
     * @param  string $doctor_id ID of a doctor in a facility (required)
     * @param  string $address_id ID of a doctor&#x60;s address in a facility (required)
     * @param  string $address_service_id ID of an address service (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateAddressServiceRequest($body, $facility_id, $doctor_id, $address_id, $address_service_id)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling updateAddressService'
            );
        }
        // verify the required parameter 'facility_id' is set
        if ($facility_id === null || (is_array($facility_id) && count($facility_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $facility_id when calling updateAddressService'
            );
        }
        // verify the required parameter 'doctor_id' is set
        if ($doctor_id === null || (is_array($doctor_id) && count($doctor_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $doctor_id when calling updateAddressService'
            );
        }
        // verify the required parameter 'address_id' is set
        if ($address_id === null || (is_array($address_id) && count($address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_id when calling updateAddressService'
            );
        }
        // verify the required parameter 'address_service_id' is set
        if ($address_service_id === null || (is_array($address_service_id) && count($address_service_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_service_id when calling updateAddressService'
            );
        }

        $resourcePath = '/facilities/{facility_id}/doctors/{doctor_id}/addresses/{address_id}/services/{address_service_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($facility_id !== null) {
            $resourcePath = str_replace(
                '{' . 'facility_id' . '}',
                ObjectSerializer::toPathValue($facility_id),
                $resourcePath
            );
        }
        // path params
        if ($doctor_id !== null) {
            $resourcePath = str_replace(
                '{' . 'doctor_id' . '}',
                ObjectSerializer::toPathValue($doctor_id),
                $resourcePath
            );
        }
        // path params
        if ($address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'address_id' . '}',
                ObjectSerializer::toPathValue($address_id),
                $resourcePath
            );
        }
        // path params
        if ($address_service_id !== null) {
            $resourcePath = str_replace(
                '{' . 'address_service_id' . '}',
                ObjectSerializer::toPathValue($address_service_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.docplanner+json; charset=UTF-8', 'application/vnd.error+docplanner+json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.docplanner+json; charset=UTF-8', 'application/vnd.error+docplanner+json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
