<?php
/**
 * BookingsScopes
 *
 * PHP version 5
 *
 * @category Class
 * @package  DocPlanner\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Docplanner Integrations API
 *
 * Welcome to Docplanner Integrations [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API!  This API gives You the ability to build Your own application and integrate it with Docplanner services.
 *
 * OpenAPI spec version: 1.8.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocPlanner\Client\Model;
use \DocPlanner\Client\ObjectSerializer;

/**
 * BookingsScopes Class Doc Comment
 *
 * @category Class
 * @package  DocPlanner\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BookingsScopes
{
    /**
     * Possible values of this enum
     */
    const BOOKINGPATIENT = 'booking.patient';
const BOOKINGADDRESS_SERVICE = 'booking.address_service';
const BOOKINGPRESENCE = 'booking.presence';
const ADDRESS_SERVICEPUBLIC_INSURANCE_FLOW = 'address_service.public_insurance_flow';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BOOKINGPATIENT,
self::BOOKINGADDRESS_SERVICE,
self::BOOKINGPRESENCE,
self::ADDRESS_SERVICEPUBLIC_INSURANCE_FLOW,        ];
    }
}
